// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGgZfGnTLyYHQE2I9_sqtiyxno3HAHCGk',
    appId: '1:828094659115:web:6de2895c33bcab8350086e',
    messagingSenderId: '828094659115',
    projectId: 'mini-projet-mobile-198ec',
    authDomain: 'mini-projet-mobile-198ec.firebaseapp.com',
    storageBucket: 'mini-projet-mobile-198ec.appspot.com',
    measurementId: 'G-P0871BK8GZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWQT8KkFm-8uchT2d0Wqqgvn-ZLbYVCCg',
    appId: '1:828094659115:android:bec1f550e58c12e950086e',
    messagingSenderId: '828094659115',
    projectId: 'mini-projet-mobile-198ec',
    storageBucket: 'mini-projet-mobile-198ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6GEpHqVyj9ts5VvPGclkKO0qG2aPORhE',
    appId: '1:828094659115:ios:2f04d1e712b23f6050086e',
    messagingSenderId: '828094659115',
    projectId: 'mini-projet-mobile-198ec',
    storageBucket: 'mini-projet-mobile-198ec.appspot.com',
    iosBundleId: 'com.example.flutterMiniProjetMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6GEpHqVyj9ts5VvPGclkKO0qG2aPORhE',
    appId: '1:828094659115:ios:2f04d1e712b23f6050086e',
    messagingSenderId: '828094659115',
    projectId: 'mini-projet-mobile-198ec',
    storageBucket: 'mini-projet-mobile-198ec.appspot.com',
    iosBundleId: 'com.example.flutterMiniProjetMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGgZfGnTLyYHQE2I9_sqtiyxno3HAHCGk',
    appId: '1:828094659115:web:9bb41786ab105e4250086e',
    messagingSenderId: '828094659115',
    projectId: 'mini-projet-mobile-198ec',
    authDomain: 'mini-projet-mobile-198ec.firebaseapp.com',
    storageBucket: 'mini-projet-mobile-198ec.appspot.com',
    measurementId: 'G-H802NC5CRL',
  );

}